### ISSUE TITLE
F keys support

### ISSUE THREAD

**Issue by BangDroid** [aironavt/global-shortcuts#4]
Is it possible to add support for F keys including up to F24?

Additionally is it possible to add a hotkey without Ctrl or Alt modifiers? Or is this a limitation with Chrome itself?

**Comment by aironavt** [comment]
Alas, these are the limitations of Chrome.

https://developer.chrome.com/docs/extensions/reference/commands/#usage

> Supported keys: A-Z, 0-9, Comma, Period, Home, End, PageUp, PageDown, Space, Insert, Delete, Arrow keys (Up, Down, Left, Right) and the Media Keys (MediaNextTrack, MediaPlayPause, MediaPrevTrack, MediaStop).

> Note: All key combinations must include either Ctrl* or Alt. Combinations that involve Ctrl+Alt are not permitted in order to avoid conflicts with the AltGr key. Shift can be used in addition to Alt or Ctrl, but is not required. Modifiers (such as Ctrl) can not be used in combination with the Media Keys. Tab key was removed from list of supported keys in Chrome version 33 and above for accessibility reasons.
